name: build to x64

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compile C Code
        run: gcc -Wall main.c -o calculator.exe

      - name: Upload calc Artifact
        uses: actions/upload-artifact@v4
        with:
          name: calculator-windows-executable
          path: calculator.exe