name: Build Calculator

on:
  push:
    tags:
      - 'v*' # יורץ כשתדחוף תגית כמו v1.0, v1.1
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Compile C code
      run: |
        gcc main.c -o calculator.exe

    - name: Upload regular Artifact
      uses: actions/upload-artifact@v4
      with:
        name: calculator-app
        path: calculator.exe

    - name: Create Release and Upload EXE
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: calculator.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}